version: 2

project_name: zocli

before:
  hooks:
    - go mod tidy

builds:
  - id: zocli
    main: ./cmd/zocli
    binary: zocli
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz

checksum:
  name_template: checksums.txt

homebrew_casks:
  - name: zocli
    directory: Casks
    homepage: https://github.com/maheshrijal/zocli
    description: Unofficial Zomato order tracker CLI
    license: MIT
    binaries:
      - zocli
    repository:
      owner: maheshrijal
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Mahesh Rijal
      email: 62394512+maheshrijal@users.noreply.github.com
